dowellnps_scale_function/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nps.urls')),
    path('stapel/', include('stapel.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nps/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import SystemSettings, Response,dowell_scale_admin,dowell_scale,dowell_scale1, default_scale, default_scale_admin,login,brand_product_error,rolescreen

app_name="nps"
router = routers.DefaultRouter()
router.register('nps-setting', viewset=SystemSettings)
router.register('nps-response', viewset=Response)
urlpatterns = [
    # path('', include(router.urls)),
    path('api/', include(router.urls)),
    path('', rolescreen,name='login_page'),
    path('nps-admin/', login,name='npslogin'),
    path('nps-admin/settings/', dowell_scale_admin,name='admin_page'),
    path('nps-scale/<str:tname>', dowell_scale, name='detail_page'),
    path('nps-scale1/<str:tname1>', dowell_scale1, name='afteradmin'),
    path('nps-scale/embed/', brand_product_error, name='error_page'),
    path('nps-scale/default/', default_scale, name='default_page'),
    path('nps-admin/default/', default_scale_admin, name='default_page_admin')
]

stapel/urls.py
from django.urls import path, include

from .views import dowell_scale_admin,dowell_scale1, default_scale, default_scale_admin,login,brand_product_error,rolescreen

app_name="stapel"

urlpatterns = [
    path('', rolescreen,name='login_page'),
    path('stapel-admin/', login,name='stapellogin'),
    path('stapel-admin/settings/', dowell_scale_admin,name='admin_page'),
    path('stapel-scale1/<str:tname1>', dowell_scale1, name='afteradmin'),
    path('stapel-scale/embed/', brand_product_error, name='error_page'),
    path('stapel-scale/default/', default_scale, name='default_page'),
    path('stapel-admin/default/', default_scale_admin, name='default_page_admin')
]

stapel/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

stapel/views.py
import random
import json
import requests
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from nps.dowellconnection import dowellconnection
from nps.login import get_user_profile
import urllib
from django.views.decorators.clickjacking import xframe_options_exempt

def dowell_scale_admin(request):
    context={}
    if request.method == 'POST':
        name = request.POST['nameofscale']
        orientation = request.POST['orientation']
        scale_upper_limit = int(request.POST['scale_upper_limit'])
        scalecolor = request.POST['scolor']
        roundcolor = request.POST['rcolor']
        fontcolor = request.POST['fcolor']
        fomat = "numbers"
        left = request.POST["left"]
        right = request.POST["right"]
        time = request.POST['time']
        spacing_unit = int(request.POST['spacing_unit'])
        text = f"{left}+{right}"
        rand_num = random.randrange(1, 10000)
        template_name = f"{name.replace(' ', '')}{rand_num}"
        scale = []
        context['scale'] = scale
        for i in range(-(scale_upper_limit), scale_upper_limit + 1):
            if i % spacing_unit == 0 and i != 0:
                scale.append(i)
        if scale_upper_limit > 10 or scale_upper_limit < 0 or spacing_unit > 5 or spacing_unit < 1:
            raise Exception("Check scale limits and spacing_unit")

        try:
            field_add={"orientation":orientation,"scale_upper_limit":scale_upper_limit,"scale_lower_limit":-scale_upper_limit,"scalecolor":scalecolor,"roundcolor":roundcolor,"fontcolor":fontcolor,"fomat":fomat,"time":time,"template_name":template_name,"name":name,"text":text, "left":left,"right":right,"scale":scale, "scale-category": "stapel scale"}
            x = dowellconnection("dowellscale","bangalore","dowellscale","scale","scale","1093","ABCDE","insert",field_add,"nil")
            print(x)

            return redirect(f"https://100035.pythonanywhere.com/stapel/stapel-scale1/{template_name}")
        except:
            context["Error"] = "Error Occurred while save the custom pl contact admin"
    return render(request, 'stapel/scale_admin.html', context)

@xframe_options_exempt
def dowell_scale1(request, tname1):
    context={}

    brand_name = request.GET.get('brand_name', None)
    product_name = request.GET.get('product_name', None)
    ls = request.path
    url = request.build_absolute_uri()
    try:
        x,s = url.split('?')
        names_values_dict = dict(x.split('=') for x in s.split('&'))
        xy = x[1].replace('&', ',')
        y = xy.replace('=', ':')
        z = '{'+y+'}'
        # return HttpResponse(names_values_dict['brand_name'])
        pls = ls.split("/")
        tname = pls[1]
        # resp = response.objects.all()
        # return HttpResponse(resp)
        context["brand_name"] = names_values_dict['brand_name']
        context["product_name"] = names_values_dict['product_name']
        context["scale_name"] = tname1
    except:
        f_path = request.get_full_path()
        response = redirect('stapel:error_page')
        response.set_cookie('url', f_path)
        return response

    context["url"]="../scaleadmin"
    context["urltext"]="Create new scale"
    context["btn"]="btn btn-dark"
    context["hist"]="Scale History"
    context["bglight"]="bg-light"
    context["left"]="border:silver 2px solid; box-shadow:2px 2px 2px 2px rgba(0,0,0,0.3)"
    # context["npsall"]=system_settings.objects.all().order_by('-id')
    field_add={"template_name":tname1}
    default = dowellconnection("dowellscale","bangalore","dowellscale","scale","scale","1093","ABCDE","fetch",field_add,"nil")
    data=json.loads(default)
    x= data["data"]
    context["defaults"]=x
    for i in x:
        context["text"]=i['text'].split("+")
        context["scale"]=i['scale']

    if request.method == 'POST':
        score = request.POST['scoretag']

        try:
            field_add={"score":score,"scale_name":context["scale_name"],"brand_name":context["brand_name"],"product_name":context["product_name"]}
            x = dowellconnection("dowellscale","bangalore","dowellscale","scale_reports","scale_reports","1094","ABCDE","insert",field_add,"nil")
            print(x)
            return redirect(f"https://100014.pythonanywhere.com/main")
        except:
            context["Error"] = "Error Occurred while save the custom pl contact admin"
    return render(request,'stapel/single_scale.html',context)

def brand_product_error(request):
    return render(request, 'stapel/error_page.html')

def default_scale(request):
    context = {}
    context["left"]="border:silver 2px solid; box-shadow:2px 2px 2px 2px rgba(0,0,0,0.3);"
    context["hist"] = "Scale History"
    context["btn"] = "btn btn-dark"
    context["urltext"] = "Create new scale"
    # context["npsall"] = system_settings.objects.all().order_by('-id')
    return render(request, 'stapel/default.html', context)

def default_scale_admin(request):
    context = {}
    context['user'] = 'admin'
    context["left"]="border:silver 2px solid; box-shadow:2px 2px 2px 2px rgba(0,0,0,0.3);height:300px;overflow-y: scroll;"
    context["hist"] = "Scale History"
    context["btn"] = "btn btn-dark"
    context["urltext"] = "Create new scale"
    try:
        field_add = {"scale-category": "stapel scale"}
        all_scales = dowellconnection("dowellscale","bangalore","dowellscale","scale","scale","1093","ABCDE","fetch",field_add,"nil")
        data = json.loads(all_scales)
        context["stapelall"] = sorted(data["data"], key=lambda d: d['_id'], reverse=True)
    except:
        print("No scales found")
    return render(request, 'stapel/default.html', context)

def rolescreen(request):
    return render(request, 'stapel/landing_page.html')

def login(request):
    url = request.GET.get('session_id', None)
    if url == None:
        return redirect("https://100014.pythonanywhere.com/")
    user=get_user_profile(url)
    if user["username"]:
        if user["role"]=='Client_Admin' or user["role"]=='TeamMember':
            response = redirect("stapel:default_page_admin")
            # response.set_cookie('role', user['role'])
            return response
        else:
            response = redirect("stapel:default_page")
            # response.set_cookie('role', user['role'])
            return response

stapel/templates/stapel/default.html
{% load i18n %}
{% load  static %}
<html lang="en">
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>VOC_STAPEL</title>
    <style>
        #horizontal{
           display: flex;
           justify-content: space-between;
           padding: 20px;
       }

        #horizontal p{
        font-size: 30px;
        padding: 5px;
        height: 60px;
        width: 60px;
        border-radius: 50%;
        margin: 5px;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        }

        #labels{
        display: flex;
        justify-content: space-between;
        }

        #countdown{
        color: black;
        float: right;
        padding: 10px 20px;
        font-size: 16px;
        }

        @media screen and (max-width: 600px) {
          #horizontal p{
            font-size: 16px;
            padding: 5px;
            height: 40px;
            width: 40px;
            border-radius: 50%;
            margin: 0.5px;
            }

           #labels{
           font-size: 20px;
           }
        }

        @media screen and (max-width: 995px) {
            #horizontal{
            padding: 10px;
            }
          #horizontal p{
            font-size: 18px;
            padding: 5px;
            height: 40px;
            width: 40px;
            margin: .5px'
            }

           #labels{
           font-size: 14px;
           }
        }
        @media screen and (max-width: 335px) {
            #horizontal{
            padding: 10px;
            }
          #horizontal p{
            font-size: 12px;
            padding: 5px;
            height: 30px;
            width: 30px;
            margin: .5px'
            }

           #labels{
           font-size: 14px;
           }
        }
    </style>
<script>
    var mbuttons =[];

$(document).ready(function() {

    // Get mbuttons list
    mbuttons = document.getElementsByClassName("number");
    console.log(mbuttons);


    if (mbuttons.length > 0) {
        for (var i = 0; i < mbuttons.length; i++) {
            mbuttons[i].addEventListener("click", function() {

               console.log(this.id);
               setrating(this.id);
            //   postScore(this.id)
            //   para = document.getElementById("lg").innerHTML=this.id;
               document.getElementById("myText").value=this.id

            });
        }

    }

});

function postScore(score){
    var xhr = new XMLHttpRequest();
    xhr.open("POST", 'https://100035.pythonanywhere.com/nps-response/', true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(JSON.stringify({
        score: parseInt(score),
        scale_name: "default",
        brand_name: "",
        user: "",
        email: "",
    }));
    window.location.replace("http://100014.pythonanywhere.com/main")
}

setrating = function(id) {
    for (var i = 0; i < mbuttons.length; i++) {
        if (+id >= +mbuttons[i].id) {
            mbuttons[i].style.color = "white";
            mbuttons[i].style.background = "#5cb85c";
        }else {
            mbuttons[i].style.color = "red";
            mbuttons[i].style.background = "#fff";
        }

    }
}
</script>
</head>
<body>

<div class="container ">
    <div class="row mt-4">
        <div class="col-sm-2 {{bglight}}" style="{% if user == 'admin' %} {{left}} {% endif %}">
            {% if user == "admin" %}
            <div class="text-dark tabl" ><h2 align="center"><u>{{hist}}</u></h2></div>
            <table>
            {% for stapel in stapelall %}
                <tr>
                    <td><a href="https://100035.pythonanywhere.com/stapel/stapel-scale1/{{stapel.template_name}}">{{stapel.template_name}}</a></td>
                </tr>
            {% endfor %}
            {% endif %}
            </table>
        </div>
        <div class="col-sm-8 bg-light" style="border:silver 2px solid; box-shadow:2px 2px 2px 2px rgba(0,0,0,0.3)" >
        <h1 align="center" class="text-danger"><b>Scale</b><span id="countdown"></span></h1><br>
            <div id="scale-container">
                <div id="horizontal" ></div>
            </div>
<!--        <div id="horizontal" ></div>-->
            <div class="pl-3" id="labels">
                   <div>Very unlikely</div>
                    <!--<div>Select score</div>-->
                    <div>Very likely</div>
            </div>
        <br>
        {% if user == "admin" %}
        <div class="pb-4">
            <a style="float:right" href="{% url 'stapel:admin_page' %}" class="{{btn}}">{{urltext}}</a>
            <br>
        </div>
        {% endif %}
    </div>
    <script>
                var vert="vertical";
                var hori="horizontal";
                var name="number";
                var n=10;

                var scale_bg = document.getElementById("horizontal")
                var sca_vert = document.getElementById("labels-vert")
                var scale_cont = document.getElementById("scale-container")
                var labels = document.getElementById("labels")
                scale_bg.style.background = '#FFD580';
                console.log('{{default.fomat|safe}}')
                star = '{{default.fomat|safe}}'

                if ('{{default.orientation|safe}}' ==="vertical" ){

                    scale_bg.style.flexDirection = "column";
                    labels.style.display = "none";
                    scale_bg.style.width = "100px";
                    scale_bg.style.margin = "auto";
                    scale_cont.style.display = "flex";
                    sca_vert.style.display = "flex";
                    scale_cont.style.width = "300px";
                    scale_cont.style.margin = "auto";
                }

                var ans = [-5,-4,-3,-2,-1,1,2,3,4,5];




                 for (let i = 0; i < ans.length; i++) {
                    const para = document.createElement("p");

                    if (star==="stars"){
                       para.innerHTML = '<i class="fa fa-star"></i>';
                    }
                    else if(star==="emoji"){
                        if (i > n/2){
                            para.innerHTML = "&#128577;";
                        }
                        else{
                            para.innerHTML = "\uD83D\uDE00";
                        }
                    }
                    else{
                        para.innerHTML = ans[i];
                    }
                    para.id=i
                    para.classList.add("number");
                    document.getElementById("horizontal").appendChild(para);
                    document.getElementById(i).style.background ='rgb(255, 239, 213)';
                    document.getElementById(i).style.color ="rgb(217, 83, 79)";
                }
                </script>
    <div class="col-sm-2"></div>
</div>
</div>
<script>
    let time = 3600;

    const countdownEl = document.getElementById("countdown");
    score = document.getElementsByClassName("number");
<!--    console.log(mbuttons);-->

    setInterval(updateCountdown, 1000)

    function updateCountdown(){
        const minutes = Math.floor(time/60);
        let seconds = time % 60;

        seconds = seconds < 10 ? '0' + seconds : seconds;

        countdownEl.innerHTML = `${minutes}:${seconds}`
        seconds < 10  && minutes == 0 ? countdownEl.style.color = "red" : countdownEl.style.color = "black" ;
        time--;
        time = time < 0 ? redirectMain() : time;
    }

    function redirectMain(){
        window.location.replace("http://100014.pythonanywhere.com/main")
    }
</script>
</body>
</html>

stapel/templates/stapel/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stapel role</title>
  <style>
    .landing-container{
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-contents: center;
    }

    .landing-header{
      color: #fff;
      font-size: 44px;
    }

    #roles{
      padding: 10px;
      font-size: 18px;
      border: none;
      outline: none;
    }
  </style>
</head>
<body style="background-color: black">
  <div class="landing-container">
    <h1 class="landing-header">Select Role</h1>
    <select id="roles" name="rolelist">
      <option selected="">Choose...</option>
      <option value="user">user</option>
      <option value="Client_Admin">Client_Admin</option>
      <option value="TeamMember">TeamMember</option>
    </select>
  </div>
</body>
<script>
  var e = document.getElementById("roles");
  function onChange() {
    var value = e.value;
    if(value == "user"){
    window.location.replace('https://100035.pythonanywhere.com/stapel/stapel-scale/default/')
    }else if(value == "Client_Admin" || value == "TeamMember" ){
    window.location.replace('https://100035.pythonanywhere.com/stapel/stapel-admin/default/')
    }else{
      console.log(value);
    }
  }
  e.onchange = onChange;
  onChange();
</script>
</html>

stapel/templates/stapel/scale.html
{% load i18n %}
{% load  static %}
<html lang="en">
<head>
{% for default in defaults %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>VOC_STAPEL</title>
    <style>
        #horizontal{
           display: flex;
           justify-content: space-between;
<!--           background: blue;-->
       }

        #horizontal p{
        font-size: 30px;
        padding: 5px;
        height: 60px;
        width: 60px;
        border-radius: 50%;
        margin: 5px;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        }

        #labels-vert{
        display: none;
        justify-content: space-between;
        flex-direction: column;
        }

        #countdown{
        color: black;
        float: right;
        padding: 10px 20px;
        font-size: 16px;
        }

        @media screen and (max-width: 600px) {
          #horizontal p{
            font-size: 16px;
            padding: 5px;
            height: 40px;
            width: 40px;
            border-radius: 50%;
            margin: 0.5px;
            }

           #labels{
           font-size: 20px;
           }
        }

        @media screen and (max-width: 995px) {
            #horizontal{
            padding: 10px;
            }
          #horizontal p{
            font-size: 18px;
            padding: 5px;
            height: 40px;
            width: 40px;
            margin: .5px'
            }

           #labels{
           font-size: 14px;
           }
        }
        @media screen and (max-width: 335px) {
            #horizontal{
            padding: 10px;
            }
          #horizontal p{
            font-size: 12px;
            padding: 5px;
            height: 30px;
            width: 30px;
            margin: .5px'
            }

           #labels{
           font-size: 14px;
           }
        }
    </style>
<script>
    var mbuttons =[];

$(document).ready(function() {

    // Get mbuttons list
    mbuttons = document.getElementsByClassName("number");
    console.log(mbuttons);


    if (mbuttons.length > 0) {
        for (var i = 0; i < mbuttons.length; i++) {
            mbuttons[i].addEventListener("click", function() {

               console.log(this.id);
               setrating(this.id);
            //   postScore(this.id)
            //   para = document.getElementById("lg").innerHTML=this.id;
            //   document.getElementById("myText").value=this.id

            });
        }

    }

});

function postScore(score){
    var xhr = new XMLHttpRequest();
    xhr.open("POST", 'https://100035.pythonanywhere.com/nps-response/', true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(JSON.stringify({
        score: parseInt(score),
        scale_name: "{{default.name|safe}}",
        brand_name: "",
        user: "",
        email: "",
    }));
    window.location.replace("http://100014.pythonanywhere.com/main")
}

setrating = function(id) {
    for (var i = 0; i < mbuttons.length; i++) {
        if (+id >= +mbuttons[i].id) {
            mbuttons[i].style.color = "white";
            mbuttons[i].style.background = "#5cb85c";
        }else {
            mbuttons[i].style.color = "red";
            mbuttons[i].style.background = "#fff";
        }

    }
}
</script>
</head>
<body>


<div class="container ">
    <div class="row mt-4">
        <div class="col-sm-2 {{bglight}}" style="{{left}}">
            <div class="text-dark"><h2 align="center"><u>{{hist}}</u></h2></div>
            <table>
            {% if user == "admin" %}
            {% for nps in npsall %}
                <tr>
        <!--            <td><a href="https://100014.pythonanywhere.com/nps/dowellscale/{{stapel.template_name}}">{{stapel.template_name}}</a></td>-->
                    <td><a href="https://100035.pythonanywhere.com/nps-scale/{{nps.template_name}}">{{nps.template_name}}</a></td>
                </tr>
            {% endfor %}
            {% endif %}
            </table>
        </div>
        <div class="col-sm-8 bg-light" style="border:silver 2px solid; box-shadow:2px 2px 2px 2px rgba(0,0,0,0.3)" >
            <h1 align="center" class="text-danger"><b>{{default.name}}</b><span id="countdown"></span></h1><br>
            <div id="scale-container">
                <div id="horizontal" ></div>
                <div class="pl-3" id="labels-vert" style="font-size:2em">
                    <div>{{text.0}}</div>
                    <div>{{text.2}}</div>
                    <div>{{text.1}}</div>
                </div>
            </div>
<!--        <div id="horizontal" ></div>-->
            <div class="pl-3" id="labels" style="font-size:2em">
                   <div style="float: left">{{text.0}}</div>
                    <div style="float: right">{{text.2}}</div>
                    <div style="margin: 0 auto; width: 30%;">{{text.1}}</div>
            </div>
        <br>
        {% if user == "admin" %}
        <div class="pb-4">
            <a style="float:right" href="{% url 'nps:admin_page' %}" class="{{btn}}">{{urltext}}</a>
            <br>
        </div>
        {% endif %}
    </div>
    <script>
                var vert="vertical";
                var hori="horizontal";
                var name="number";
                var n=10;

                var scale_bg = document.getElementById("horizontal")
                var sca_vert = document.getElementById("labels-vert")
                var scale_cont = document.getElementById("scale-container")
                var labels = document.getElementById("labels")
                scale_bg.style.background = '{{default.scalecolor|safe}}';
                scale_bg.style.padding = "20px 20px";
                console.log('{{default.fomat|safe}}')
                star = '{{default.fomat|safe}}'

                if ('{{default.orientation|safe}}' ==="vertical" ){

                    scale_bg.style.flexDirection = "column";
                    labels.style.display = "none";
                    scale_bg.style.width = "100px";
                    scale_bg.style.margin = "auto";
                    scale_cont.style.display = "flex";
                    sca_vert.style.display = "flex";
                    scale_cont.style.width = "300px";
                    scale_cont.style.margin = "auto";
                }
                for (let i = 1; i <= n; i++) {
                    const para = document.createElement("p");

                    if (star==="stars"){
                       para.innerHTML = '<i class="fa fa-star"></i>';
                    }
                    else if(star==="emoji"){
                        para.innerHTML = '<i class="far fa-grin"></i>';
                    }
                    else{
                        para.innerHTML = i;
                    }
                    para.id=i
                    para.classList.add("number");
                    document.getElementById("horizontal").appendChild(para);
<!--                    document.getElementById(i).innerHTML = i;-->
                    document.getElementById(i).style.background ='{{default.roundcolor|safe}}';
                    document.getElementById(i).style.color ="{{default.fontcolor|safe }}";
                }
                </script>
        <script>
            let time = {{default.time|safe}};

            const countdownEl = document.getElementById("countdown");

            setInterval(updateCountdown, 1000)

            function updateCountdown(){
                const minutes = Math.floor(time/60);
                let seconds = time % 60;

                seconds = seconds < 10 ? '0' + seconds : seconds;

                countdownEl.innerHTML = `${minutes}:${seconds}`
                seconds < 10 && minutes == 0 ? countdownEl.style.color = "red" : countdownEl.style.color = "black" ;
                time--;
                time = time < 0 ? redirectMain() : time;
            }

            function redirectMain(){
                window.location.replace("http://100014.pythonanywhere.com/main")
            }
        </script>
    <div class="col-sm-2"></div>
    {% endfor %}
</div>
</div>
</body>